# ref: http://docs.travis-ci.com/user/build-configuration

language: c

before_install:
    - wget "http://www.lua.org/ftp/lua-5.3.2.tar.gz" && tar xzf lua-5.3.2.tar.gz && cd lua-5.3.2 && sudo make linux test install;
    - wget "https://github.com/mongodb/libbson/releases/download/1.3.6/libbson-1.3.6.tar.gz" && tar xzf libbson-$ver.tar.gz && ./configure && make && sudo make instsall;

install:
    - cd $TRAVIS_BUILD_DIR
    - make all

script:
    - make test
